# Generated by Django 4.1.4 on 2022-12-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('mnum', models.CharField(max_length=12)),
                ('pwd', models.CharField(max_length=8)),
            ],
        ),
    ]
